FROM jenkins:1.609.1

#USER root
#RUN curl -sSL https://get.docker.com/ | sh  && \
#    curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
#    usermod -aG docker jenkins
